production:
    dialect: postgres
    datasource: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/vitrine?sslmode=disable
    dir: devops/migrations
    table: migrations

docker:
    dialect: postgres
    datasource: postgres://postgres@postgres:5432/vitrine?sslmode=disable
    dir: devops/migrations
    table: migrations
