version: "3"

volumes:
  gopath:

services:
  postgres:
    image: postgres:9-alpine
    volumes:
      - ./:/vitrine
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vitrine
  golang:
    image: golang:1.11
    volumes:
      - ./:/vitrine-social
      - ${GOPATH:-gopath}:/go
    ports:
      - "8000:8000"
    environment:
      API_PORT: 8000
      DATABASE_HOST: postgres
      VITRINESOCIAL_ENV: ${VITRINESOCIAL_ENV:-dev}
      STORAGE_S3_ENDPOINT: http://minio:9000
    command: sh -c "while true; do echo 'beep'; sleep 5; done"
    working_dir: /vitrine-social
    links:
      - postgres
  minio:
    image: minio/minio:RELEASE.2018-10-18T00-28-58Z
    environment:
      MINIO_ACCESS_KEY: configAccessKeyId
      MINIO_SECRET_KEY: configSecretKey
    volumes:
      - "./.data/minio:/data"
      - "./.data/minio-config:/root/.minio"
    ports:
      - "${MINIO_PORT:-9000}:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/images.vitrinesocial.test /data/vitrinesocial.test && /usr/bin/minio server /data'
  images-server:
    image: halverneus/static-file-server:latest
    volumes:
      - "./.data/minio/images.vitrinesocial.test:/web"
    ports:
      - 7000:8080
    depends_on:
      - minio
